### ISSUE TITLE
Getting type error takes 1 positional argument but 2 were given while using classifier.classify('img_path')

### ISSUE THREAD

**Issue by amshrbo** [bedapudi6788/NudeNet#101]
**TypeError: __array__() takes 1 positional argument but 2 were given**
when trying to use the classify method I get this error

**The code snippet which gave this error***
```python
clf.classify('/home/shrbo/Downloads/dtest.jpeg')
```
**libraries versions**
1. nudenet==2.0.9
2. numpy==1.21.0

**Expected behavior**
The nsfw score

**Output**
ERROR:root:Error reading /home/shrbo/Downloads/dtest.jpeg __array__() takes 1 positional argument but 2 were given
Traceback (most recent call last):
  File "/home/shrbo/venvpy/nudetest/lib/python3.7/site-packages/nudenet/image_utils.py", line 134, in load_images
    image = img_to_array(image)
  File "/home/shrbo/venvpy/nudetest/lib/python3.7/site-packages/nudenet/image_utils.py", line 102, in img_to_array
    x = np.asarray(img, dtype=dtype)
TypeError: __array__() takes 1 positional argument but 2 were given
Out[3]: {}

**This Solution only worked on older version that I've installed,  doesn't work on newly created ones**
uninstalling nudenet==2.0.9 
Installing nudenet==2.0.8
The numpy version after installing 2.0.8 is numpy==1.20.3
The problem solved

**Comment by amshrbo** [comment]
**The Solution**
- The problem seems to come from the **pillow package** so I just downgraded it to an older version Pillow==8.2.0
- If there is anyone can explain to me why downgrading pillow solved the problem I will be more than happy for his explanation. 
- So just got ahead and install this old version  `pip install Pillow==8.2.0`
