### ISSUE TITLE
in_browser "Can't create a session"

### ISSUE THREAD

**Issue by RWOverdijk** [bedapudi6788/NudeNet#125]
I'm probably just missing something. I cloned the repo, ran `yarn install` followed by `yarn start` and I get the error "Can't create a session"

```
Uncaught runtime errors:
×
ERROR
Can't create a session
    at t.createSessionFinalize (http://localhost:3000/static/js/bundle.js:27527:110)
    at t.createSession (http://localhost:3000/static/js/bundle.js:27550:46)
    at t.createSession (http://localhost:3000/static/js/bundle.js:27175:17)
    at t.OnnxruntimeWebAssemblySessionHandler.loadModel (http://localhost:3000/static/js/bundle.js:27267:100)
    at async Object.createSessionHandler (http://localhost:3000/static/js/bundle.js:17006:20)
    at async d.create (http://localhost:3000/static/js/bundle.js:16955:19)
    at async Object.App (http://localhost:3000/static/js/bundle.js:68:20)
```

**Comment by RWOverdijk** [comment]
Oh, there's more stuff. It thinks every face is female. I tried some of the manliest pictures but it is sure they're female.

**Comment by jabedzaman** [comment]
> I'm probably just missing something. I cloned the repo, ran `yarn install` followed by `yarn start` and I get the error "Can't create a session"
> 
> ```
> Uncaught runtime errors:
> ×
> ERROR
> Can't create a session
>     at t.createSessionFinalize (http://localhost:3000/static/js/bundle.js:27527:110)
>     at t.createSession (http://localhost:3000/static/js/bundle.js:27550:46)
>     at t.createSession (http://localhost:3000/static/js/bundle.js:27175:17)
>     at t.OnnxruntimeWebAssemblySessionHandler.loadModel (http://localhost:3000/static/js/bundle.js:27267:100)
>     at async Object.createSessionHandler (http://localhost:3000/static/js/bundle.js:17006:20)
>     at async d.create (http://localhost:3000/static/js/bundle.js:16955:19)
>     at async Object.App (http://localhost:3000/static/js/bundle.js:68:20)
> ```

how u got it running later?

**Comment by RWOverdijk** [comment]
By not using the browser I think. I don't remember, it's been a while and I stopped trying. I built my own 😅
