### ISSUE TITLE
Unable to install nudenet module

### ISSUE THREAD

**Issue by Adjenz** [bedapudi6788/NudeNet#45]
Hi,

I have lot of errors when trying to install the nudenet module. Let me show you : 

`pip show tensorflow
WARNING: Package(s) not found: tensorflow`

`pip show keras
WARNING: Package(s) not found: keras`

`C:\Users\a.******\AppData\Local\Programs\Python\Python38\Scripts>pip install nudenet
Collecting nudenet
  Using cached NudeNet-2.0.1-py2.py3-none-any.whl (21 kB)
Collecting keras-retinanet==0.5.1
  Using cached keras-retinanet-0.5.1.tar.gz (61 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\a.******\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\a.******\\AppData\\Local\\Temp\\pip-install-l72vxg_w\\keras-retinanet\\setup.py'"'"'; __file__='"'"'C:\\Users\\a.******\\AppData\\Local\\Temp\\pip-install-l72vxg_w\\keras-retinanet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\a.******\AppData\Local\Temp\pip-pip-egg-info-kpcg3ikb'
         cwd: C:\Users\a.******\AppData\Local\Temp\pip-install-l72vxg_w\keras-retinanet\
    Complete output (193 lines):
    Processing numpy/random\_bounded_integers.pxd.in
    Processing numpy/random\bit_generator.pyx
    Processing numpy/random\mtrand.pyx
    Processing numpy/random\_bounded_integers.pyx.in
    Processing numpy/random\_common.pyx
    Processing numpy/random\_generator.pyx
    Processing numpy/random\_mt19937.pyx
    Processing numpy/random\_pcg64.pyx
    Processing numpy/random\_philox.pyx
    Processing numpy/random\_sfc64.pyx
    Cythonizing sources
    Could not locate executable g77
    Could not locate executable f77
    Could not locate executable ifort
    Could not locate executable ifl
    Could not locate executable f90
    Could not locate executable DF
    Could not locate executable efl
    Could not locate executable gfortran
    Could not locate executable f95
    Could not locate executable g95
    Could not locate executable efort
    Could not locate executable efc
    Could not locate executable flang
    don't know how to compile Fortran code on platform 'nt'
    non-existing path in 'numpy\\distutils': 'site.cfg'
    Running from numpy source directory.
    C:\Users\A26E3~1.THE\AppData\Local\Temp\easy_install-8i4trsem\numpy-1.19.1\setup.py:470: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    C:\Users\A26E3~1.THE\AppData\Local\Temp\easy_install-8i4trsem\numpy-1.19.1\numpy\distutils\system_info.py:1914: UserWarning:
        Optimized (vendor) Blas libraries are not found.
        Falls back to netlib Blas library which has worse performance.
        A better performance should be easily gained by switching
        Blas library.
      if self._calc_info(blas):
    C:\Users\A26E3~1.THE\AppData\Local\Temp\easy_install-8i4trsem\numpy-1.19.1\numpy\distutils\system_info.py:1914: UserWarning:
        Blas (http://www.netlib.org/blas/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [blas]) or by setting
        the BLAS environment variable.
      if self._calc_info(blas):
    C:\Users\A26E3~1.THE\AppData\Local\Temp\easy_install-8i4trsem\numpy-1.19.1\numpy\distutils\system_info.py:1914: UserWarning:
        Blas (http://www.netlib.org/blas/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [blas_src]) or by setting
        the BLAS_SRC environment variable.
      if self._calc_info(blas):
    C:\Users\A26E3~1.THE\AppData\Local\Temp\easy_install-8i4trsem\numpy-1.19.1\numpy\distutils\system_info.py:1748: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
    C:\Users\A26E3~1.THE\AppData\Local\Temp\easy_install-8i4trsem\numpy-1.19.1\numpy\distutils\system_info.py:1748: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      return getattr(self, '_calc_info_{}'.format(name))()
    c:\users\a.******\appdata\local\programs\python\python38\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\setuptools\msvc.py", line 489, in _find_latest_available_vc_ver
        return self.find_available_vc_vers()[-1]
    IndexError: list index out of range

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\bdist_egg.py", line 163, in run
        self.run_command("egg_info")
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\A26E3~1.THE\AppData\Local\Temp\easy_install-8i4trsem\numpy-1.19.1\numpy\distutils\command\egg_info.py", line 24, in run
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\A26E3~1.THE\AppData\Local\Temp\easy_install-8i4trsem\numpy-1.19.1\numpy\distutils\command\build_src.py", line 144, in run
      File "C:\Users\A26E3~1.THE\AppData\Local\Temp\easy_install-8i4trsem\numpy-1.19.1\numpy\distutils\command\build_src.py", line 155, in build_sources
      File "C:\Users\A26E3~1.THE\AppData\Local\Temp\easy_install-8i4trsem\numpy-1.19.1\numpy\distutils\command\build_src.py", line 288, in build_library_sources
      File "C:\Users\A26E3~1.THE\AppData\Local\Temp\easy_install-8i4trsem\numpy-1.19.1\numpy\distutils\command\build_src.py", line 378, in generate_sources
      File "numpy\core\setup.py", line 650, in get_mathlib_info
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\distutils\command\config.py", line 241, in try_link
        self._check_compiler()
      File "C:\Users\A26E3~1.THE\AppData\Local\Temp\easy_install-8i4trsem\numpy-1.19.1\numpy\distutils\command\config.py", line 52, in _check_compiler
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\distutils\_msvccompiler.py", line 224, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
        return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\setuptools\msvc.py", line 843, in __init__
        self.si = SystemInfo(self.ri, vc_ver)
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\setuptools\msvc.py", line 485, in __init__
        self.vc_ver = vc_ver or self._find_latest_available_vc_ver()
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\setuptools\msvc.py", line 492, in _find_latest_available_vc_ver
        raise distutils.errors.DistutilsPlatformError(err)
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "C:\Users\A26E3~1.THE\AppData\Local\Temp\easy_install-8i4trsem\numpy-1.19.1\setup.py", line 499, in <module>
      File "C:\Users\A26E3~1.THE\AppData\Local\Temp\easy_install-8i4trsem\numpy-1.19.1\setup.py", line 491, in setup_package
      File "C:\Users\A26E3~1.THE\AppData\Local\Temp\easy_install-8i4trsem\numpy-1.19.1\numpy\distutils\core.py", line 169, in setup
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\distutils\core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 253, in run_setup
        raise
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\setuptools\_vendor\six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "C:\Users\A26E3~1.THE\AppData\Local\Temp\easy_install-8i4trsem\numpy-1.19.1\setup.py", line 499, in <module>
      File "C:\Users\A26E3~1.THE\AppData\Local\Temp\easy_install-8i4trsem\numpy-1.19.1\setup.py", line 491, in setup_package
      File "C:\Users\A26E3~1.THE\AppData\Local\Temp\easy_install-8i4trsem\numpy-1.19.1\numpy\distutils\core.py", line 169, in setup
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\distutils\core.py", line 163, in setup
        raise SystemExit("error: " + str(msg))
    SystemExit: error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\a.******\AppData\Local\Temp\pip-install-l72vxg_w\keras-retinanet\setup.py", line 45, in <module>
        setuptools.setup(
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\setuptools\dist.py", line 716, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
        return installer(requirement)
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\setuptools\dist.py", line 786, in fetch_build_egg
        return cmd.easy_install(req)
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "c:\users\a.******\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 1146, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

**Comment by bedapudi6788** [comment]
Oh! I haven't tested this on windows and unfortunately keras-retinanet has a lot of dependencies that might not go well with windows.

**Comment by Adjenz** [comment]
> Oh! I haven't tested this on windows and unfortunately keras-retinanet has a lot of dependencies that might not go well with windows.

I installed an Ubuntu on a VM, now it works. Thanks for your help :)

**Comment by bedapudi6788** [comment]
@Screamus57 with the latest version, nudenet only requires tensorflow <= 1.15.4 to be installed on your system. You should be able to run nudenet>=2.0.6 on windows without any issues.
