### ISSUE TITLE
    ModuleNotFoundError: No module named 'numpy'

### ISSUE THREAD

**Issue by LinArcX** [bedapudi6788/NudeNet#5]
Hi. error when installing nudenet via pip:
```
sudo pip install nudenet
[sudo] password for linarcx: 
Collecting nudenet
  Downloading https://files.pythonhosted.org/packages/23/04/9183baf731ab4408d940b21e70c71308f1e9bc9fe7a780790f83c526ae2d/NudeNet-1.0.4-py2.py3-none-any.whl
Collecting opencv-python==4.0.0.21 (from nudenet)
  Downloading https://files.pythonhosted.org/packages/45/bd/e0a4391ac105ecf73a6e14372174b05774634c7c6454e49c38750d516eee/opencv_python-4.0.0.21-cp37-cp37m-manylinux1_x86_64.whl (25.4MB)
     |████████████████████████████████| 25.4MB 25kB/s 
Collecting keras-retinanet==0.5.0 (from nudenet)
  Downloading https://files.pythonhosted.org/packages/28/bc/1e926156e950073af90f9347cb74bf4a75e749942e75f398472bad7ef146/keras-retinanet-0.5.0.tar.gz (59kB)
     |████████████████████████████████| 61kB 55kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-5wyi37hq/keras-retinanet/setup.py", line 3, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-5wyi37hq/keras-retinanet/
```

**Comment by bedapudi6788** [comment]
Can you just install numpy separately and check
